version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-artifact:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
