export enum EventType {
  DebugChanged,
  ServerAuthenticated,
  ServerConnected,
  ServerNotification,
  ServerDisconnected,
  MatchAdvertised,
  PlayerConnected,
  HostDisconnected,
  PlayerDisconnected,
  Countdown,
  GoalStart,
  GoalEnd,
  GameOverStart,
  GameOverEnd,
}
